{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "app-deploy.labels" $ | nindent 4 }}
type: {{ .type | default "Opaque" }}
data:
  {{- if eq .type "kubernetes.io/dockerconfigjson" }}
  .dockerconfigjson: {{ .dockerConfigJson | quote }}
  {{- else }}
  {{- range $key, $val := .data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}