{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-deploy.fullname" . }}
  labels:
    {{- include "app-deploy.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.dockerConfigJson.encodedPassword | quote }}}}
{{- end }}